#!/bin/bash

echo "What's your favorite color? "
  read text1
echo "What's your bestfriends favorite color? "
  read text2

    if test $text1 != text2; then
echo " I guess opposites do attract. "
    else
echo " You two do think alike! "
